### ISSUE TITLE
Support Rspec Rails 4

### ISSUE THREAD

**Issue by iarie** [civiccc/db-query-matchers#38]
https://relishapp.com/rspec/rspec-rails/docs/upgrade

> RSpec Rails 4 is a major version under semantic versioning, it allowed us to change the supported Rails versions to 5 and 6 only. There are no changes required to upgrade to RSpec Rails 4 if you are using Rails 5 or 6.

Could the gemspec restriction be eased without any issue?

**Comment by trotzig** [comment]
Hi @iarie! I'm one of the people who contributed to this library. I think few of the contributors are still using this library (not because it's bad, just that we use different tech today). If you want to see this change happen, your best option is to make a PR for it. I don't have write access (so I can't merge) but I think I can help get things published to rubygems.

**Comment by sds** [comment]
Constraint relaxed in #34.
